# Generated by Django 4.2.6 on 2023-10-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_pr_lan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_lan',
            name='actuality',
            field=models.CharField(choices=[('Actual', 'Actual'), ('50 to 50', '50 to 50'), ('old', 'old')], default='Actual', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pr_lan',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
